# Generated by Django 5.0.10 on 2024-12-10 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Car Manufacturer')),
                ('model', models.CharField(max_length=50, verbose_name='Car Model')),
                ('version', models.CharField(max_length=50, verbose_name='Car Version')),
                ('odometer', models.PositiveIntegerField(default=0, help_text='Mileage', verbose_name='Car Odometer')),
                ('colour', models.CharField(max_length=20, verbose_name='Car Colour')),
                ('number_of_doors', models.PositiveSmallIntegerField(default=5, verbose_name='Car Number of Doors')),
                ('number_of_seats', models.PositiveSmallIntegerField(default=5, verbose_name='Car Number of Seats')),
                ('engine_displacement', models.PositiveIntegerField(help_text='Engine displacement in cubic centimeters (cc)', verbose_name='Car Engine Displacement')),
                ('power', models.PositiveIntegerField(help_text='Engine power in horsepower (hp)', verbose_name='Car Power')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2024)], verbose_name='Car Year')),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('C', 'Certified Pre-Owned'), ('T', 'Totaled')], default='U', max_length=20, verbose_name='Car Condition')),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid'), ('PL', 'Plug-In Hybrid'), ('C', 'CNG'), ('L', 'LPG'), ('HY', 'Hydrogen'), ('ET', 'Ethanol')], default='P', max_length=20, verbose_name='Car Fuel Type')),
                ('transmission_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('C', 'CVT'), ('D', 'Dual Clutch'), ('S', 'Semi-Automatic')], default='M', max_length=20, verbose_name='Car Transmission Type')),
                ('drive_type', models.CharField(choices=[('FR', 'Front (FWD)'), ('R', 'Rear (RWD)'), ('A', 'All (AWD)'), ('F', 'Four (FWD)')], default='FR', max_length=20, verbose_name='Car Drive Type')),
            ],
        ),
        migrations.CreateModel(
            name='CarDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=256, unique=True)),
                ('description', models.TextField(blank=True, default='No description available.', verbose_name='Description')),
                ('main_photo', models.URLField(blank=True, null=True, verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{1,4}?[-.\\s]??\\(?\\d{1,3}?\\)?[-.\\s]??\\d{1,4}[-.\\s]??\\d{1,4}[-.\\s]??\\d{1,9}$')], verbose_name='Contact')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='cardeals.car', verbose_name='Car')),
            ],
        ),
    ]
