# Generated by Django 5.0.10 on 2024-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=4234235425, editable=False, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
