services:
  docs:
    image: projekt_zespolowy_local_docs
    container_name: projekt_zespolowy_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./projekt_zespolowy:/app/projekt_zespolowy:z
    ports:
      - '9000:9000'
    command: /start-docs
